name: Reuse Other Workflow
on:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: '@chtristanswitchthink'

  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "current-time is ${{ needs.call-workflow.outputs.current-time }}"
